//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Common/ComDefine.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterInfo")]
  public partial class CharacterInfo : global::ProtoBuf.IExtensible
  {
    public CharacterInfo() {}
    
    private string _channelId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private uint _charId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _diamond;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharacterState")]
  public partial class CharacterState : global::ProtoBuf.IExtensible
  {
    public CharacterState() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _isQZ = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isQZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isQZ
    {
      get { return _isQZ; }
      set { _isQZ = value; }
    }
    private uint _isZB = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isZB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isZB
    {
      get { return _isZB; }
      set { _isZB = value; }
    }
    private uint _isFangQiQZ = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isFangQiQZ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isFangQiQZ
    {
      get { return _isFangQiQZ; }
      set { _isFangQiQZ = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _restGold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"restGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restGold
    {
      get { return _restGold; }
      set { _restGold = value; }
    }
    private int _restDiamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"restDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restDiamond
    {
      get { return _restDiamond; }
      set { _restDiamond = value; }
    }
    private int _xiazhu = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"xiazhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xiazhu
    {
      get { return _xiazhu; }
      set { _xiazhu = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XZDDRule")]
  public partial class XZDDRule : global::ProtoBuf.IExtensible
  {
    public XZDDRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD> _flags = new global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD>();
    [global::ProtoBuf.ProtoMember(1, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.XZDDRule.XZDD> flags
    {
      get { return _flags; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"XZDD")]
    public enum XZDD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJD", Value=1)]
      ZMJD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DYJJD", Value=3)]
      DYJJD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H3Z", Value=4)]
      H3Z = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_ZM", Value=5)]
      DGH_ZM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_FP", Value=6)]
      DGH_FP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TDH", Value=7)]
      TDH = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XLCHRule")]
  public partial class XLCHRule : global::ProtoBuf.IExtensible
  {
    public XLCHRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH> _xlch = new global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH>();
    [global::ProtoBuf.ProtoMember(1, Name=@"xlch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.XLCHRule.XLCH> xlch
    {
      get { return _xlch; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"XLCH")]
    public enum XLCH
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJD", Value=1)]
      ZMJD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DYJJD", Value=3)]
      DYJJD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"H3Z", Value=4)]
      H3Z = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_ZM", Value=5)]
      DGH_ZM = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DGH_FP", Value=6)]
      DGH_FP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TDH", Value=7)]
      TDH = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DDHRule")]
  public partial class DDHRule : global::ProtoBuf.IExtensible
  {
    public DDHRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH> _ddh = new global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ddh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.DDHRule.DDH> ddh
    {
      get { return _ddh; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DDH")]
    public enum DDH
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DPH", Value=1)]
      DPH = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMH", Value=2)]
      ZMH = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"THIRtRule")]
  public partial class THIRtRule : global::ProtoBuf.IExtensible
  {
    public THIRtRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.THIRtRule.THIRt> _thirt = new global::System.Collections.Generic.List<ProtoBuf.THIRtRule.THIRt>();
    [global::ProtoBuf.ProtoMember(1, Name=@"thirt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.THIRtRule.THIRt> thirt
    {
      get { return _thirt; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"THIRt")]
    public enum THIRt
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GJFF", Value=1)]
      GJFF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THRee", Value=2)]
      THRee = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TPYEONE", Value=3)]
      TPYEONE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MaCard", Value=4)]
      MaCard = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DERule")]
  public partial class DERule : global::ProtoBuf.IExtensible
  {
    public DERule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.DERule.DE> _de = new global::System.Collections.Generic.List<ProtoBuf.DERule.DE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"de", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.DERule.DE> de
    {
      get { return _de; }
    }
  
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"DE")]
    public enum DE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GJFF", Value=1)]
      GJFF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=2)]
      ZMJF = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZHJF", Value=3)]
      ZHJF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FPBPCJ", Value=4)]
      FPBPCJ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMALL", Value=5)]
      SMALL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MIDDLE", Value=6)]
      MIDDLE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIG", Value=7)]
      BIG = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LZMJRule")]
  public partial class LZMJRule : global::ProtoBuf.IExtensible
  {
    public LZMJRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.LZMJRule.LZMJ> _lzmj = new global::System.Collections.Generic.List<ProtoBuf.LZMJRule.LZMJ>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lzmj", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.LZMJRule.LZMJ> lzmj
    {
      get { return _lzmj; }
    }
  
    private uint _fishNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fishNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fishNum
    {
      get { return _fishNum; }
      set { _fishNum = value; }
    }
    private uint _roundNUM;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roundNUM", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNUM
    {
      get { return _roundNUM; }
      set { _roundNUM = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LZMJ")]
    public enum LZMJ
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEMQING", Value=1)]
      MEMQING = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"XWMJRule")]
  public partial class XWMJRule : global::ProtoBuf.IExtensible
  {
    public XWMJRule() {}
    
    private readonly global::System.Collections.Generic.List<ProtoBuf.XWMJRule.XWMJ> _xwmj = new global::System.Collections.Generic.List<ProtoBuf.XWMJRule.XWMJ>();
    [global::ProtoBuf.ProtoMember(1, Name=@"xwmj", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ProtoBuf.XWMJRule.XWMJ> xwmj
    {
      get { return _xwmj; }
    }
  
    private uint _maxFan;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxFan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxFan
    {
      get { return _maxFan; }
      set { _maxFan = value; }
    }
    private uint _baseScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"baseScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint baseScore
    {
      get { return _baseScore; }
      set { _baseScore = value; }
    }
    private uint _hongZhongNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hongZhongNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hongZhongNum
    {
      get { return _hongZhongNum; }
      set { _hongZhongNum = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"XWMJ")]
    public enum XWMJ
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZMJF", Value=1)]
      ZMJF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DianPaoHu", Value=2)]
      DianPaoHu = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ZiMoHu", Value=3)]
      ZiMoHu = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XQue", Value=4)]
      XQue = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChampionPay", Value=5)]
      ChampionPay = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ThreePlayer", Value=6)]
      ThreePlayer = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomRuleInfo")]
  public partial class MJRoomRuleInfo : global::ProtoBuf.IExtensible
  {
    public MJRoomRuleInfo() {}
    
    private ProtoBuf.MJRoomRule _gameRule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.MJRoomRule gameRule
    {
      get { return _gameRule; }
      set { _gameRule = value; }
    }
    private ProtoBuf.XZDDRule _xzddRule = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"xzddRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.XZDDRule xzddRule
    {
      get { return _xzddRule; }
      set { _xzddRule = value; }
    }
    private ProtoBuf.XLCHRule _xlchRule = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"xlchRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.XLCHRule xlchRule
    {
      get { return _xlchRule; }
      set { _xlchRule = value; }
    }
    private ProtoBuf.DDHRule _ddhRule = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ddhRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.DDHRule ddhRule
    {
      get { return _ddhRule; }
      set { _ddhRule = value; }
    }
    private ProtoBuf.DERule _deRule = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.DERule deRule
    {
      get { return _deRule; }
      set { _deRule = value; }
    }
    private ProtoBuf.XWMJRule _xwmjRule = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"xwmjRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.XWMJRule xwmjRule
    {
      get { return _xwmjRule; }
      set { _xwmjRule = value; }
    }
    private ProtoBuf.THIRtRule _thirtRule = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"thirtRule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.THIRtRule thirtRule
    {
      get { return _thirtRule; }
      set { _thirtRule = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChiPai")]
  public partial class ChiPai : global::ProtoBuf.IExtensible
  {
    public ChiPai() {}
    
    private uint _chitype = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chitype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chitype
    {
      get { return _chitype; }
      set { _chitype = value; }
    }
    private uint _cardo = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardo
    {
      get { return _cardo; }
      set { _cardo = value; }
    }
    private uint _cardt = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cardt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardt
    {
      get { return _cardt; }
      set { _cardt = value; }
    }
    private uint _cards = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cards
    {
      get { return _cards; }
      set { _cards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJCardsInfo")]
  public partial class MJCardsInfo : global::ProtoBuf.IExtensible
  {
    public MJCardsInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _pengCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"pengCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> pengCards
    {
      get { return _pengCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _mingGangCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"mingGangCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> mingGangCards
    {
      get { return _mingGangCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _anGangCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"anGangCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> anGangCards
    {
      get { return _anGangCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _huCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"huCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huCards
    {
      get { return _huCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _passCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"passCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> passCards
    {
      get { return _passCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zOut = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"x3zOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zOut
    {
      get { return _x3zOut; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zIn = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"x3zIn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zIn
    {
      get { return _x3zIn; }
    }
  
    private ProtoBuf.MJCardType _xQue = ProtoBuf.MJCardType.MJ_CARD_TYPE_WAN;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"xQue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(ProtoBuf.MJCardType.MJ_CARD_TYPE_WAN)]
    public ProtoBuf.MJCardType xQue
    {
      get { return _xQue; }
      set { _xQue = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _tingCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"tingCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> tingCards
    {
      get { return _tingCards; }
    }
  
    private bool _hasBaoTing = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"hasBaoTing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool hasBaoTing
    {
      get { return _hasBaoTing; }
      set { _hasBaoTing = value; }
    }
    private uint _roundRestCardNum = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"roundRestCardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roundRestCardNum
    {
      get { return _roundRestCardNum; }
      set { _roundRestCardNum = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.ChiPai> _chiCards = new global::System.Collections.Generic.List<ProtoBuf.ChiPai>();
    [global::ProtoBuf.ProtoMember(14, Name=@"chiCards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ChiPai> chiCards
    {
      get { return _chiCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _weiCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(15, Name=@"weiCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> weiCards
    {
      get { return _weiCards; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _feiPengCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(16, Name=@"feiPengCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> feiPengCards
    {
      get { return _feiPengCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomCacheChar")]
  public partial class MJRoomCacheChar : global::ProtoBuf.IExtensible
  {
    public MJRoomCacheChar() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oriCharId = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oriCharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint oriCharId
    {
      get { return _oriCharId; }
      set { _oriCharId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _opList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"opList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> opList
    {
      get { return _opList; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _cardList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> cardList
    {
      get { return _cardList; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _gangList = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"gangList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> gangList
    {
      get { return _gangList; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.ChiPai> _ChiList = new global::System.Collections.Generic.List<ProtoBuf.ChiPai>();
    [global::ProtoBuf.ProtoMember(6, Name=@"ChiList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.ChiPai> ChiList
    {
      get { return _ChiList; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _gangCatag = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"gangCatag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> gangCatag
    {
      get { return _gangCatag; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomCaching")]
  public partial class MJRoomCaching : global::ProtoBuf.IExtensible
  {
    public MJRoomCaching() {}
    
    private readonly global::System.Collections.Generic.List<uint> _huCharIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"huCharIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huCharIds
    {
      get { return _huCharIds; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _huTypes = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"huTypes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> huTypes
    {
      get { return _huTypes; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar> _charList = new global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar>();
    [global::ProtoBuf.ProtoMember(3, Name=@"charList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJRoomCacheChar> charList
    {
      get { return _charList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomInfo")]
  public partial class MJRoomInfo : global::ProtoBuf.IExtensible
  {
    public MJRoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.MJRoomRuleInfo _roomRuleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRuleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.MJRoomRuleInfo roomRuleInfo
    {
      get { return _roomRuleInfo; }
      set { _roomRuleInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo> _cardsInfos = new global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJCardsInfo> cardsInfos
    {
      get { return _cardsInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> _charInfos = new global::System.Collections.Generic.List<ProtoBuf.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"charInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> charInfos
    {
      get { return _charInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _charIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"charIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIds
    {
      get { return _charIds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterState> _charStates = new global::System.Collections.Generic.List<ProtoBuf.CharacterState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"charStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterState> charStates
    {
      get { return _charStates; }
    }
  
    private uint _zjId = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zjId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zjId
    {
      get { return _zjId; }
      set { _zjId = value; }
    }
    private uint _inGame = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"inGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inGame
    {
      get { return _inGame; }
      set { _inGame = value; }
    }
    private ProtoBuf.MJRoomCaching _roomCache = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"roomCache", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.MJRoomCaching roomCache
    {
      get { return _roomCache; }
      set { _roomCache = value; }
    }
    private uint _cardDirection = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"cardDirection", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardDirection
    {
      get { return _cardDirection; }
      set { _cardDirection = value; }
    }
    private uint _cardPosition = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"cardPosition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cardPosition
    {
      get { return _cardPosition; }
      set { _cardPosition = value; }
    }
    private uint _restCardNum = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"restCardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint restCardNum
    {
      get { return _restCardNum; }
      set { _restCardNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachPBPlayer")]
  public partial class EachPBPlayer : global::ProtoBuf.IExtensible
  {
    public EachPBPlayer() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private uint _queType = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"queType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint queType
    {
      get { return _queType; }
      set { _queType = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _x3zCardIn = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"x3zCardIn", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zCardIn
    {
      get { return _x3zCardIn; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _x3zCardOut = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"x3zCardOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> x3zCardOut
    {
      get { return _x3zCardOut; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachPBPlayerOP")]
  public partial class EachPBPlayerOP : global::ProtoBuf.IExtensible
  {
    public EachPBPlayerOP() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _oricharId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"oricharId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oricharId
    {
      get { return _oricharId; }
      set { _oricharId = value; }
    }
    private ProtoBuf.MJGameOP _op;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.MJGameOP op
    {
      get { return _op; }
      set { _op = value; }
    }
    private uint _card = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _rest = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rest
    {
      get { return _rest; }
      set { _rest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJPlayBack")]
  public partial class MJPlayBack : global::ProtoBuf.IExtensible
  {
    public MJPlayBack() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachPBPlayer> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP> _opInfo = new global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP>();
    [global::ProtoBuf.ProtoMember(4, Name=@"opInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachPBPlayerOP> opInfo
    {
      get { return _opInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EachRoundPlayer")]
  public partial class EachRoundPlayer : global::ProtoBuf.IExtensible
  {
    public EachRoundPlayer() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _position = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _gold;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private int _restGold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"restGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restGold
    {
      get { return _restGold; }
      set { _restGold = value; }
    }
    private int _restDiamond = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"restDiamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restDiamond
    {
      get { return _restDiamond; }
      set { _restDiamond = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoundRecord")]
  public partial class MJRoundRecord : global::ProtoBuf.IExtensible
  {
    public MJRoundRecord() {}
    
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private ulong _roundOverTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundOverTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roundOverTime
    {
      get { return _roundOverTime; }
      set { _roundOverTime = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> _players = new global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.EachRoundPlayer> players
    {
      get { return _players; }
    }
  
    private ProtoBuf.MJPlayBack _playBack = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playBack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ProtoBuf.MJPlayBack playBack
    {
      get { return _playBack; }
      set { _playBack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MJRoomRecord")]
  public partial class MJRoomRecord : global::ProtoBuf.IExtensible
  {
    public MJRoomRecord() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.GameType _gameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.GameType gameType
    {
      get { return _gameType; }
      set { _gameType = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord> _rounds = new global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.MJRoundRecord> rounds
    {
      get { return _rounds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharFriend")]
  public partial class CharFriend : global::ProtoBuf.IExtensible
  {
    public CharFriend() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _portrait = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string portrait
    {
      get { return _portrait; }
      set { _portrait = value; }
    }
    private float _winRate = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"winRate", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float winRate
    {
      get { return _winRate; }
      set { _winRate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharFriendList")]
  public partial class CharFriendList : global::ProtoBuf.IExtensible
  {
    public CharFriendList() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharFriend> _friendList = new global::System.Collections.Generic.List<ProtoBuf.CharFriend>();
    [global::ProtoBuf.ProtoMember(2, Name=@"friendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharFriend> friendList
    {
      get { return _friendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharInfoDync")]
  public partial class CharInfoDync : global::ProtoBuf.IExtensible
  {
    public CharInfoDync() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private uint _diamond = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private uint _param1 = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _param2 = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _param3 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }
    private int _param4 = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"param4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int param4
    {
      get { return _param4; }
      set { _param4 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SGRoomRuleInfo")]
  public partial class SGRoomRuleInfo : global::ProtoBuf.IExtensible
  {
    public SGRoomRuleInfo() {}
    
    private ProtoBuf.SGRoomRule _gameRule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.SGRoomRule gameRule
    {
      get { return _gameRule; }
      set { _gameRule = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SGCardsInfo")]
  public partial class SGCardsInfo : global::ProtoBuf.IExtensible
  {
    public SGCardsInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SGRoomInfo")]
  public partial class SGRoomInfo : global::ProtoBuf.IExtensible
  {
    public SGRoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.SGRoomRuleInfo _roomRuleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRuleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.SGRoomRuleInfo roomRuleInfo
    {
      get { return _roomRuleInfo; }
      set { _roomRuleInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.SGCardsInfo> _cardsInfos = new global::System.Collections.Generic.List<ProtoBuf.SGCardsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.SGCardsInfo> cardsInfos
    {
      get { return _cardsInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> _charInfos = new global::System.Collections.Generic.List<ProtoBuf.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"charInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> charInfos
    {
      get { return _charInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _charIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"charIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIds
    {
      get { return _charIds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterState> _charStates = new global::System.Collections.Generic.List<ProtoBuf.CharacterState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"charStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterState> charStates
    {
      get { return _charStates; }
    }
  
    private uint _zjId = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zjId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zjId
    {
      get { return _zjId; }
      set { _zjId = value; }
    }
    private uint _inGame = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"inGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inGame
    {
      get { return _inGame; }
      set { _inGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNRoomRuleInfo")]
  public partial class NNRoomRuleInfo : global::ProtoBuf.IExtensible
  {
    public NNRoomRuleInfo() {}
    
    private ProtoBuf.NNRoomRule _gameRule;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameRule", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ProtoBuf.NNRoomRule gameRule
    {
      get { return _gameRule; }
      set { _gameRule = value; }
    }
    private uint _roundNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roundNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roundNum
    {
      get { return _roundNum; }
      set { _roundNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNCardsInfo")]
  public partial class NNCardsInfo : global::ProtoBuf.IExtensible
  {
    public NNCardsInfo() {}
    
    private uint _charId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"charId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charId
    {
      get { return _charId; }
      set { _charId = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _handCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> handCards
    {
      get { return _handCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NNRoomInfo")]
  public partial class NNRoomInfo : global::ProtoBuf.IExtensible
  {
    public NNRoomInfo() {}
    
    private uint _roomId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private ProtoBuf.NNRoomRuleInfo _roomRuleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomRuleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.NNRoomRuleInfo roomRuleInfo
    {
      get { return _roomRuleInfo; }
      set { _roomRuleInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.NNCardsInfo> _cardsInfos = new global::System.Collections.Generic.List<ProtoBuf.NNCardsInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cardsInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.NNCardsInfo> cardsInfos
    {
      get { return _cardsInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> _charInfos = new global::System.Collections.Generic.List<ProtoBuf.CharacterInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"charInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterInfo> charInfos
    {
      get { return _charInfos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _charIds = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"charIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> charIds
    {
      get { return _charIds; }
    }
  
    private readonly global::System.Collections.Generic.List<ProtoBuf.CharacterState> _charStates = new global::System.Collections.Generic.List<ProtoBuf.CharacterState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"charStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.CharacterState> charStates
    {
      get { return _charStates; }
    }
  
    private uint _zjId = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zjId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint zjId
    {
      get { return _zjId; }
      set { _zjId = value; }
    }
    private uint _inGame = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"inGame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint inGame
    {
      get { return _inGame; }
      set { _inGame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PROTOCOL_VERSION_UPPER")]
    public enum PROTOCOL_VERSION_UPPER
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTOCOL_VERSION_CURRENT", Value=1)]
      PROTOCOL_VERSION_CURRENT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PROTOCOL_VERSION_LOWER")]
    public enum PROTOCOL_VERSION_LOWER
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROTOCOL_VERSION_LOWER_LIMIT", Value=1)]
      PROTOCOL_VERSION_LOWER_LIMIT = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERetCode")]
    public enum ERetCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_SUCCESS", Value=0)]
      RET_SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RET_FAIL", Value=1)]
      RET_FAIL = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PingConfig")]
    public enum PingConfig
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_PING_INTERVAL", Value=9)]
      CLIENT_PING_INTERVAL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_PING_INTERVAL", Value=9)]
      SERVER_PING_INTERVAL = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameType")]
    public enum GameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_NULL", Value=0)]
      GT_NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_GC", Value=1)]
      GT_GC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_MJ", Value=2)]
      GT_MJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_DE", Value=4)]
      GT_DE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_XWMJ", Value=8)]
      GT_XWMJ = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GT_THIRt", Value=16)]
      GT_THIRt = 16
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJCardType")]
    public enum MJCardType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_WAN", Value=1)]
      MJ_CARD_TYPE_WAN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_TONG", Value=2)]
      MJ_CARD_TYPE_TONG = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_TIAO", Value=3)]
      MJ_CARD_TYPE_TIAO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_FENG", Value=4)]
      MJ_CARD_TYPE_FENG = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_ZI", Value=5)]
      MJ_CARD_TYPE_ZI = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_CARD_TYPE_HUA", Value=6)]
      MJ_CARD_TYPE_HUA = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJRoomRule")]
    public enum MJRoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_XZDD", Value=1)]
      MJ_ROOM_RULE_XZDD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_XLCH", Value=2)]
      MJ_ROOM_RULE_XLCH = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_DDH", Value=3)]
      MJ_ROOM_RULE_DDH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_DE", Value=4)]
      MJ_ROOM_RULE_DE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_ROOM_RULE_XWMJ", Value=5)]
      MJ_ROOM_RULE_XWMJ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CD_ROOM_RULE_THURt", Value=6)]
      CD_ROOM_RULE_THURt = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJOPErrorCode")]
    public enum MJOPErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_1", Value=1)]
      MJ_OP_ERROR_1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_2", Value=2)]
      MJ_OP_ERROR_2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_3", Value=3)]
      MJ_OP_ERROR_3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_4", Value=4)]
      MJ_OP_ERROR_4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_5", Value=5)]
      MJ_OP_ERROR_5 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_6", Value=6)]
      MJ_OP_ERROR_6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_7", Value=7)]
      MJ_OP_ERROR_7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_8", Value=8)]
      MJ_OP_ERROR_8 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_9", Value=9)]
      MJ_OP_ERROR_9 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_10", Value=10)]
      MJ_OP_ERROR_10 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_11", Value=11)]
      MJ_OP_ERROR_11 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_12", Value=12)]
      MJ_OP_ERROR_12 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_13", Value=13)]
      MJ_OP_ERROR_13 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_14", Value=14)]
      MJ_OP_ERROR_14 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_15", Value=15)]
      MJ_OP_ERROR_15 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_16", Value=16)]
      MJ_OP_ERROR_16 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_17", Value=17)]
      MJ_OP_ERROR_17 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_18", Value=18)]
      MJ_OP_ERROR_18 = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_19", Value=19)]
      MJ_OP_ERROR_19 = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ERROR_20", Value=20)]
      MJ_OP_ERROR_20 = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MJGameOP")]
    public enum MJGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_PREP", Value=1)]
      MJ_OP_PREP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ZJ", Value=2)]
      MJ_OP_ZJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_XQ", Value=3)]
      MJ_OP_XQ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_MOPAI", Value=4)]
      MJ_OP_MOPAI = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_CHUPAI", Value=5)]
      MJ_OP_CHUPAI = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GUO", Value=6)]
      MJ_OP_GUO = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_PENG", Value=7)]
      MJ_OP_PENG = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG", Value=8)]
      MJ_OP_GANG = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG2", Value=9)]
      MJ_OP_GANG2 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG3", Value=10)]
      MJ_OP_GANG3 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_GANG4", Value=11)]
      MJ_OP_GANG4 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_HU", Value=12)]
      MJ_OP_HU = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TING", Value=13)]
      MJ_OP_TING = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_CHI", Value=14)]
      MJ_OP_CHI = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ROUND_OVER", Value=15)]
      MJ_OP_ROUND_OVER = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_VOTE_JSROOM", Value=16)]
      MJ_OP_VOTE_JSROOM = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_VOTE_RESULT", Value=17)]
      MJ_OP_VOTE_RESULT = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_ON_LINE", Value=18)]
      MJ_OP_ON_LINE = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_PLAYER_OP_RESULT", Value=19)]
      MJ_PLAYER_OP_RESULT = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_FEI", Value=20)]
      MJ_OP_FEI = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TI", Value=21)]
      MJ_OP_TI = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TI2", Value=22)]
      MJ_OP_TI2 = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TI3", Value=23)]
      MJ_OP_TI3 = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_TI4", Value=24)]
      MJ_OP_TI4 = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MJ_OP_NULL", Value=25)]
      MJ_OP_NULL = 25
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DEGameOP")]
    public enum DEGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_PREP", Value=1)]
      DZP_OP_PREP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_ZJ", Value=2)]
      DZP_OP_ZJ = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_MOPAI", Value=3)]
      DZP_OP_MOPAI = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_CHUPAI", Value=4)]
      DZP_OP_CHUPAI = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_GUO", Value=5)]
      DZP_OP_GUO = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_PENG", Value=6)]
      DZP_OP_PENG = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_ZHAO", Value=7)]
      DZP_OP_ZHAO = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_HU", Value=8)]
      DZP_OP_HU = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_TING", Value=9)]
      DZP_OP_TING = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_CHI", Value=10)]
      DZP_OP_CHI = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_BCARD", Value=11)]
      DZP_OP_BCARD = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_ROUND_OVER", Value=12)]
      DZP_OP_ROUND_OVER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_VOTE_JSROOM", Value=13)]
      DZP_OP_VOTE_JSROOM = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_VOTE_RESULT", Value=14)]
      DZP_OP_VOTE_RESULT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_ON_LINE", Value=15)]
      DZP_OP_ON_LINE = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_PLAYER_OP_RESULT", Value=16)]
      DZP_PLAYER_OP_RESULT = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DZP_OP_NULL", Value=17)]
      DZP_OP_NULL = 17
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"THIRTGameOP")]
    public enum THIRTGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_PREP", Value=1)]
      THIRT_OP_PREP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_GUO", Value=2)]
      THIRT_OP_GUO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_HU", Value=3)]
      THIRT_OP_HU = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_TING", Value=4)]
      THIRT_OP_TING = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_START_THAN", Value=5)]
      THIRT_OP_START_THAN = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_NOW_THAN_OVER", Value=6)]
      THIRT_OP_NOW_THAN_OVER = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THURT_OP_STATE_WEATE", Value=7)]
      THURT_OP_STATE_WEATE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THURT_OP_STATE_SHOOT", Value=8)]
      THURT_OP_STATE_SHOOT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THURT_OP_STATE_HOMERUN", Value=9)]
      THURT_OP_STATE_HOMERUN = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_ROUND_OVER", Value=10)]
      THIRT_OP_ROUND_OVER = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_VOTE_JSROOM", Value=11)]
      THIRT_OP_VOTE_JSROOM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_VOTE_RESULT", Value=12)]
      THIRT_OP_VOTE_RESULT = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_ON_LINE", Value=13)]
      THIRT_OP_ON_LINE = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_PLAYER_OP_RESULT", Value=14)]
      THIRT_PLAYER_OP_RESULT = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THIRT_OP_NULL", Value=15)]
      THIRT_OP_NULL = 15
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SGRoomRule")]
    public enum SGRoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_ROOM_RULE_QZ", Value=1)]
      SG_ROOM_RULE_QZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_ROOM_RULE_DZ", Value=2)]
      SG_ROOM_RULE_DZ = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SGGameOP")]
    public enum SGGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_QZ", Value=1)]
      SG_OP_QZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_PREP", Value=2)]
      SG_OP_PREP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_ZJ_FAPAI_CMD", Value=3)]
      SG_OP_ZJ_FAPAI_CMD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_XZ", Value=4)]
      SG_OP_XZ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_QP", Value=5)]
      SG_OP_QP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_KP", Value=6)]
      SG_OP_KP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_KP_DJS", Value=7)]
      SG_OP_KP_DJS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_ZJ_DJS", Value=8)]
      SG_OP_ZJ_DJS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_ZJ", Value=9)]
      SG_OP_ZJ = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_ZJ_KEYI_FAPAI", Value=10)]
      SG_OP_ZJ_KEYI_FAPAI = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_EXITROOM", Value=11)]
      SG_OP_EXITROOM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_ROUND_OVER", Value=12)]
      SG_OP_ROUND_OVER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_VOTE_JSROOM", Value=13)]
      SG_OP_VOTE_JSROOM = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SG_OP_VOTE_RESULT", Value=14)]
      SG_OP_VOTE_RESULT = 14
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NNRoomRule")]
    public enum NNRoomRule
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_ROOM_RULE_QZ", Value=1)]
      NN_ROOM_RULE_QZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_ROOM_RULE_DZ", Value=2)]
      NN_ROOM_RULE_DZ = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NNGameOP")]
    public enum NNGameOP
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_QZ", Value=1)]
      NN_OP_QZ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_PREP", Value=2)]
      NN_OP_PREP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_ZJ_FAPAI_CMD", Value=3)]
      NN_OP_ZJ_FAPAI_CMD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_XZ", Value=4)]
      NN_OP_XZ = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_QP", Value=5)]
      NN_OP_QP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_KP", Value=6)]
      NN_OP_KP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_KP_DJS", Value=7)]
      NN_OP_KP_DJS = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_ZJ_DJS", Value=8)]
      NN_OP_ZJ_DJS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_ZJ", Value=9)]
      NN_OP_ZJ = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_ZJ_KEYI_FAPAI", Value=10)]
      NN_OP_ZJ_KEYI_FAPAI = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_EXITROOM", Value=11)]
      NN_OP_EXITROOM = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_ROUND_OVER", Value=12)]
      NN_OP_ROUND_OVER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_VOTE_JSROOM", Value=13)]
      NN_OP_VOTE_JSROOM = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NN_OP_VOTE_RESULT", Value=14)]
      NN_OP_VOTE_RESULT = 14
    }
  
}